- hosts: localhost
  gather_facts: false
  tasks:
    - name: Create zuul-config project
      include_role:
        name: create_project
      vars:
        project: zuul-config
    - name: Create test1 project
      include_role:
        name: create_project
      vars:
        project: test1
    - name: Create test2 project
      include_role:
        name: create_project
      vars:
        project: test2
